export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_TOP_PERFORMANCES_BEGIN = "GET_TOP_PERFORMANCES_BEGIN";
export const GET_TOP_PERFORMANCES_SUCCESS = "GET_TOP_PERFORMANCES_SUCCESS";
export const GET_TOP_PERFORMANCES_FAILURE = "GET_TOP_PERFORMANCES_FAILURE";
export const GET_RECENT_PERFORMANCES_BEGIN = "GET_RECENT_PERFORMANCES_BEGIN";
export const GET_RECENT_PERFORMANCES_SUCCESS =
  "GET_RECENT_PERFORMANCES_SUCCESS";
export const GET_RECENT_PERFORMANCES_FAILURE =
  "GET_RECENT_PERFORMANCES_FAILURE";
